In [2]:
# Import pandas dan data
import pandas as pd
path = 'Rice Production Indonesia 2020-2022.csv'
df = pd.read_csv(path)

In [3]:
# Mengubah nama kolom agar mudah dimengerti
dict_rename = {'Year':'Tahun',
 'Yield.Areal(ha)':'Luas Lahan (Ha)',
 'Productivity(kw/ha)':'Produktivitas (Ton/Ha)',
 'Production.(ton)': 'Produksi (Ton)'}

df.rename(columns=dict_rename, inplace=True)
df

,Provinsi,Tahun,Luas Lahan (Ha),Produktivitas (Ton/Ha),Produksi (Ton)
0,ACEH,2020,317869.41,55.28,1757313.07
1,SUMATERA UTARA,2020,388591.22,52.51,2040500.19
2,SUMATERA BARAT,2020,295664.47,46.92,1387269.29
3,RIAU,2020,64733.13,37.64,243685.04
4,JAMBI,2020,84772.93,45.58,386413.49
...,...,...,...,...,...
97,SULAWESI BARAT,2022,69323.95,50.99,353513.30
98,MALUKU,2022,23987.82,38.60,92601.06
99,MALUKU UTARA,2022,6416.45,38.16,24486.03
100,PAPUA BARAT,2022,5460.59,43.89,23963.92
101,PAPUA,2022,49741.91,38.99,193943.50

## 1. Perbandingan total produksi dari tahun 2020 sampai 2022

In [9]:
df.groupby(['Provinsi','Tahun'])[['Produksi (Ton)','Produktivitas (Ton/Ha)']].sum()

                        Produksi (Ton)  Produktivitas (Ton/Ha)
Provinsi         Tahun
ACEH             2020       1757313.07                   55.28
                 2021       1634639.60                   55.03
                 2022       1509456.00                   55.55
BALI             2020        532168.45                   58.49
                 2021        618910.81                   58.83
...                                ...                     ...
SUMATERA SELATAN 2021       2552443.19                   51.44
                 2022       2775069.00                   54.06
SUMATERA UTARA   2020       2040500.19                   52.51
                 2021       2004142.51                   52.00
                 2022       2088584.00                   50.76

[102 rows x 2 columns]

## 2. Perbadingan produktivitas setiap provinsi

In [4]:
# Provinsi paling produktif
df.groupby('Provinsi')['Produktivitas (Ton/Ha)'].mean().sort_values(ascending=False).head(5)

Provinsi
BALI           59.303333
JAWA BARAT     56.793333
JAWA TENGAH    56.343333
JAWA TIMUR     56.320000
ACEH           55.286667
Name: Produktivitas (Ton/Ha), dtype: float64

In [5]:
# Provinsi paling tidak produktif
df.groupby('Provinsi')['Produktivitas (Ton/Ha)'].mean().sort_values(ascending=False).tail(5)

Provinsi
KALIMANTAN TIMUR     36.480000
KALIMANTAN UTARA     34.400000
KALIMANTAN TENGAH    31.340000
KALIMANTAN BARAT     30.836667
KEP. RIAU            29.483333
Name: Produktivitas (Ton/Ha), dtype: float64

## 3. Persentase produksi beras di Indonesia berdasarkan Provinsi di Tahun 2022

In [6]:
# Mengambil Data Tahun 2022
df_2022 = df[df['Tahun'] == 2022].copy()
df_2022.reset_index(drop=True, inplace=True)

In [7]:
# Mencari total produksi
total_produksi = df_2022['Produksi (Ton)'].sum()

In [8]:
# Membuat fungsi perhitungan persentase produksi
def persentase_produksi(prod):
  return (prod / total_produksi) * 100

In [9]:
# Mengaplikasi fungsi persentase produksi pada kolom
df_2022['Persentase Produksi'] = df_2022['Produksi (Ton)'].apply(persentase_produksi)
df_2022.sort_values(by='Persentase Produksi', ascending=False).head(5)

,Provinsi,Tahun,Luas Lahan (Ha),Produktivitas (Ton/Ha),Produksi (Ton),Persentase Produksi
14,JAWA TIMUR,2022,1693211.0,56.26,9526516.0,17.400355
11,JAWA BARAT,2022,1662404.0,56.75,9433723.0,17.230867
12,JAWA TENGAH,2022,1688670.0,55.41,9356445.0,17.089717
26,SULAWESI SELATAN,2022,1038084.0,51.64,5360169.0,9.790446
5,SUMATERA SELATAN,2022,513378.2,54.06,2775069.0,5.068714

In [10]:
df_2022.sort_values(by='Persentase Produksi', ascending=False).tail(5)

,Provinsi,Tahun,Luas Lahan (Ha),Produktivitas (Ton/Ha),Produksi (Ton),Persentase Produksi
23,KALIMANTAN UTARA,2022,8604.19,35.49,30533.59,0.055770
31,MALUKU UTARA,2022,6416.45,38.16,24486.03,0.044724
32,PAPUA BARAT,2022,5460.59,43.89,23963.92,0.043771
10,DKI JAKARTA,2022,477.25,48.98,2337.77,0.004270
9,KEP. RIAU,2022,179.48,28.24,506.91,0.000926